# Generated by Django 5.1.7 on 2025-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_remove_booking_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
